name: TubesZB MGM24 OpenThread RCP
device: MGM240PA32VNN
base_project: src/openthread_rcp
filename: "{manifest_name}_{ot_rcp_version}_{baudrate}_{fw_variant}"
sdk: "simplicity_sdk:2025.6.2"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: openthread_rcp
  ot_rcp_version: dynamic
  baudrate: 921600
  fw_variant: hw_flow

c_defines:
  SL_IOSTREAM_USART_VCOM_BAUDRATE: 921600
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlCtsAndRts

  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_TX_PIN:  6

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RX_PIN:  5

  SL_IOSTREAM_USART_VCOM_CTS_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  7

  SL_IOSTREAM_USART_VCOM_RTS_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  8

  SL_CLOCK_MANAGER_HFXO_EN: 1
  SL_CLOCK_MANAGER_HFXO_CTUNE: 140
  SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE: SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE_HFXO

  SL_RAIL_UTIL_RSSI_OFFSET: 0
