name: TubesZB MGM21 2023 Zigbee
device: MGM240PA32VNN
base_project: src/zigbee_ncp
sdk: "gecko_sdk:4.4.6"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: ncp-uart-hw
  dynamic: ["ezsp_version"]
  baudrate: 115200
  fw_variant: sw_flow

configuration:
  SL_RAIL_UTIL_PTI_MODE: RAIL_PTI_MODE_DISABLED # enabled in original tubeszb fw
  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlNone

c_defines:
  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_TX_PIN:  6

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RX_PIN:  5

  SL_IOSTREAM_USART_VCOM_CTS_PORT: gpioPortC
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  1

  SL_IOSTREAM_USART_VCOM_RTS_PORT: gpioPortD
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  2

  SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE: 64
  
  EMBER_APS_UNICAST_MESSAGE_COUNT: 32
  EMBER_BROADCAST_TABLE_SIZE: 64
  EMBER_NEIGHBOR_TABLE_SIZE: 26
  EMBER_SOURCE_ROUTE_TABLE_SIZE: 254

