name: TubesZB BM24 OpenThread RCP
device: EFR32MG24A420F1536IM48
base_project: src/openthread_rcp
filename: "{manifest_name}_{ot_rcp_version.split('/')[-1]}_gsdk_{sdk_version}"
sdk: simplicity_sdk:2026.6.1
toolchain: gcc:14.2.1.20241119
gbl:
  fw_type: openthread_rcp
  ot_rcp_version: dynamic
  baudrate: 460800
c_defines:
  OPENTHREAD_CONFIG_NCP_TX_BUFFER_SIZE:
    type: c_flag
    value: 4096
  SL_IOSTREAM_EUSART_VCOM_BAUDRATE: 460800
  SL_IOSTREAM_EUSART_VCOM_FLOW_CONTROL_TYPE: SL_IOSTREAM_EUSART_UART_FLOW_CTRL_CTS_RTS
  SL_IOSTREAM_EUSART_VCOM_PERIPHERAL: EUSART0
  SL_IOSTREAM_EUSART_VCOM_PERIPHERAL_NO: 0
  SL_IOSTREAM_EUSART_VCOM_TX_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_EUSART_VCOM_TX_PIN: 6
  SL_IOSTREAM_EUSART_VCOM_RX_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_EUSART_VCOM_RX_PIN: 5
  SL_IOSTREAM_EUSART_VCOM_CTS_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_EUSART_VCOM_CTS_PIN: 7
  SL_IOSTREAM_EUSART_VCOM_RTS_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_EUSART_VCOM_RTS_PIN: 8
  SL_IOSTREAM_EUSART_VCOM_RX_BUFFER_SIZE: 512
  SL_CLOCK_MANAGER_HFXO_EN: 1
  SL_CLOCK_MANAGER_HFXO_CTUNE: 140
  SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE: SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE_HFXO
  SL_RAIL_UTIL_RSSI_OFFSET: 0
sdk_patches:
- disable_gp_rx_filter.patch
- uart_tx_drop_on_timeout.patch
- uart_tx_bounded_wait_eusart.patch
sdk_extension:
- id: watchdog
  version: 1.0.0
  vendor: nabucasa
add_components:
- id: watchdog
  vendor: nabucasa
  package: watchdog
