name: TubesZB BM MG24B2 OpenThread RCP
device: EFR32MG24A420F1536IM48
base_project: src/openthread_rcp
filename: "{manifest_name}_{ot_rcp_version.split('/')[-1]}_gsdk_{sdk_version}"
sdk: "gecko_sdk:4.4.6"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: openthread_rcp
  ot_rcp_version: dynamic
  baudrate: 460800

add_components:
- id: simple_led
  instance: [board_activity]

c_defines:
  SL_UARTDRV_USART_VCOM_PERIPHERAL: USART0
  SL_UARTDRV_USART_VCOM_PERIPHERAL_NO: 0
  SL_UARTDRV_USART_VCOM_BAUDRATE: 460800

  SL_UARTDRV_USART_VCOM_TX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_TX_PIN:  6

  SL_UARTDRV_USART_VCOM_RX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_RX_PIN:  5

  SL_UARTDRV_USART_VCOM_CTS_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_CTS_PIN:  7

  SL_UARTDRV_USART_VCOM_RTS_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_RTS_PIN:  8

  SL_SIMPLE_LED_BOARD_ACTIVITY_POLARITY: SL_SIMPLE_LED_POLARITY_ACTIVE_LOW
  SL_SIMPLE_LED_BOARD_ACTIVITY_PORT:     gpioPortD
  SL_SIMPLE_LED_BOARD_ACTIVITY_PIN:      2

  SL_DEVICE_INIT_HFXO_CTUNE:  92