name: TubesZB MGM24 Zigbee Router
device: MGM240PA32VNN
base_project: src/zigbee_router
filename: '{manifest_name}_{sdk_version}_{baudrate}_{fw_variant}'
sdk: simplicity_sdk:2026.6.1
toolchain: gcc:14.2.1.20241119
gbl:
  fw_type: zigbee_router
  baudrate: 460800
  fw_variant: hw_flow
sdk_extension:
- id: tubeszb_router
  vendor: TubesZB
  version: 1.0.0
remove_components:
- id: iostream_usart
  instance:
  - vcom
add_components:
- id: iostream_eusart
  instance:
  - vcom
- id: simple_led
  instance:
  - led0
- id: simple_button
  instance:
  - btn1
- id: tubeszb_router_callbacks
  vendor: TubesZB
  package: tubeszb_router
- id: rail_util_rssi
- id: zigbee_concentrator
- id: zigbee_identify
c_defines:
  SL_ZIGBEE_BROADCAST_TABLE_SIZE: 30
  SL_ZIGBEE_NEIGHBOR_TABLE_SIZE: 26
  SL_ZIGBEE_BINDING_TABLE_SIZE: 32
  SL_ZIGBEE_GP_PROXY_TABLE_SIZE: 10
  SL_ZIGBEE_KEY_TABLE_SIZE: 1
  SL_ZIGBEE_SOURCE_ROUTE_TABLE_SIZE: 254
  SL_ZIGBEE_AF_PLUGIN_NETWORK_STEERING_CHANNEL_MASK: 134215680
  SL_ZIGBEE_AF_PLUGIN_NETWORK_STEERING_RADIO_TX_POWER: 19
  SL_ZIGBEE_AF_PLUGIN_CONCENTRATOR_CONCENTRATOR_TYPE: HIGH_RAM_CONCENTRATOR
  SL_ZIGBEE_AF_PLUGIN_CONCENTRATOR_MIN_TIME_BETWEEN_BROADCASTS_SECONDS: 30
  SL_ZIGBEE_AF_PLUGIN_CONCENTRATOR_MAX_TIME_BETWEEN_BROADCASTS_SECONDS: 180
  SL_ZIGBEE_AF_PLUGIN_CONCENTRATOR_ROUTE_ERROR_THRESHOLD: 3
  SL_ZIGBEE_AF_PLUGIN_CONCENTRATOR_DELIVERY_FAILURE_THRESHOLD: 1
  SL_ZIGBEE_ADDRESS_TABLE_SIZE: 64
  SL_ZIGBEE_APS_UNICAST_MESSAGE_COUNT: 128
  SL_ZIGBEE_MAX_END_DEVICE_CHILDREN: 64
  SL_ZIGBEE_APS_DUPLICATE_REJECTION_MAX_ENTRIES: 64
  SL_IOSTREAM_EUSART_VCOM_BAUDRATE: 460800
  SL_IOSTREAM_EUSART_VCOM_FLOW_CONTROL_TYPE: SL_IOSTREAM_EUSART_UART_FLOW_CTRL_CTS_RTS
  SL_IOSTREAM_EUSART_VCOM_PERIPHERAL: EUSART0
  SL_IOSTREAM_EUSART_VCOM_PERIPHERAL_NO: 0
  SL_IOSTREAM_EUSART_VCOM_TX_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_EUSART_VCOM_TX_PIN: 6
  SL_IOSTREAM_EUSART_VCOM_RX_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_EUSART_VCOM_RX_PIN: 5
  SL_IOSTREAM_EUSART_VCOM_CTS_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_EUSART_VCOM_CTS_PIN: 7
  SL_IOSTREAM_EUSART_VCOM_RTS_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_EUSART_VCOM_RTS_PIN: 8
  SL_SIMPLE_LED_LED0_POLARITY: SL_SIMPLE_LED_POLARITY_ACTIVE_LOW
  SL_SIMPLE_LED_LED0_PORT: SL_GPIO_PORT_D
  SL_SIMPLE_LED_LED0_PIN: 2
  SL_SIMPLE_BUTTON_BTN1_MODE: SL_SIMPLE_BUTTON_MODE_INTERRUPT
  SL_SIMPLE_BUTTON_BTN1_PORT: SL_GPIO_PORT_A
  SL_SIMPLE_BUTTON_BTN1_PIN: 0
  SL_CLOCK_MANAGER_HFXO_EN: 1
  SL_CLOCK_MANAGER_HFXO_CTUNE: 140
  SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE: SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE_HFXO
  SL_RAIL_UTIL_RSSI_OFFSET: 0
  SL_IOSTREAM_EUSART_VCOM_RX_BUFFER_SIZE: 64
  SL_ZIGBEE_MULTICAST_TABLE_SIZE:
    type: c_flag
    value: 26
  SL_ZIGBEE_ROUTE_TABLE_SIZE:
    type: c_flag
    value: 16
  SL_ZIGBEE_DISCOVERY_TABLE_SIZE:
    type: c_flag
    value: 16
config_file:
- path: config/zcl/zcl_config.zap
  file_id: zap_configuration_file_id
  directory: zcl
