name: SMLIGHT SLZB-06MG24 Zigbee NCP
device: EFR32MG24A020F1024IM40
base_project: src/zigbee_ncp
filename: "{manifest_name}_{ezsp_version}_{baudrate}_{fw_variant}"
sdk: "simplicity_sdk:2025.6.2"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: zigbee_ncp
  ezsp_version: dynamic
  baudrate: 115200
  fw_variant: sw_flow

c_defines:
  SL_IOSTREAM_EUSART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_EUSART_VCOM_FLOW_CONTROL_TYPE: SL_IOSTREAM_EUSART_UART_FLOW_CTRL_SOFT

  SL_IOSTREAM_EUSART_VCOM_PERIPHERAL: EUSART0
  SL_IOSTREAM_EUSART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_EUSART_VCOM_TX_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_EUSART_VCOM_TX_PIN: 5

  SL_IOSTREAM_EUSART_VCOM_RX_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_EUSART_VCOM_RX_PIN: 6

  SL_IOSTREAM_EUSART_VCOM_CTS_PORT: 0
  SL_IOSTREAM_EUSART_VCOM_CTS_PIN: 0

  SL_IOSTREAM_EUSART_VCOM_RTS_PORT: 0
  SL_IOSTREAM_EUSART_VCOM_RTS_PIN: 0

  SL_CLOCK_MANAGER_HFXO_EN: 1
  SL_CLOCK_MANAGER_HFXO_CTUNE: 140
  SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE: SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE_HFXO

  SL_RAIL_UTIL_RSSI_OFFSET: 0
