name: SMLIGHT SLZB-07 Zigbee Router
device: EFR32MG21A020F768IM32
base_project: src/zigbee_router
filename: "{manifest_name}_{ezsp_version}_{baudrate}_{fw_variant}"
sdk: "simplicity_sdk:2025.6.2"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: zigbee_router
  ezsp_version: dynamic
  baudrate: 115200
  fw_variant: sw_flow

add_components:
  # Status
  - id: simple_led
    instance:
      - led0

c_defines:
  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: uartFlowControlSoftware

  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_USART_VCOM_TX_PIN: 6

  SL_IOSTREAM_USART_VCOM_RX_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_USART_VCOM_RX_PIN: 5

  SL_IOSTREAM_USART_VCOM_CTS_PORT: 0
  SL_IOSTREAM_USART_VCOM_CTS_PIN: 0

  SL_IOSTREAM_USART_VCOM_RTS_PORT: 0
  SL_IOSTREAM_USART_VCOM_RTS_PIN: 0

  SL_SIMPLE_LED_LED0_POLARITY: SL_SIMPLE_LED_POLARITY_ACTIVE_HIGH
  SL_SIMPLE_LED_LED0_PORT: SL_GPIO_PORT_C
  SL_SIMPLE_LED_LED0_PIN: 0

  SL_CLOCK_MANAGER_HFXO_EN: 1
  SL_CLOCK_MANAGER_HFXO_CTUNE: 140
  SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE: SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE_HFXO

  SL_RAIL_UTIL_RSSI_OFFSET: -11
