name: NabuCasa ZBT-2 Zigbee Router
device: EFR32MG24A420F1536IM40
base_project: src/zigbee_router
filename: "{manifest_name}_{ezsp_version}_{baudrate}_{fw_variant}"
sdk: "simplicity_sdk:2025.6.2"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: zigbee_router
  ezsp_version: dynamic
  baudrate: 115200
  fw_variant: sw_flow

add_components:
  # BOOT
  - id: simple_button
    instance:
      - btn1

c_defines:
  SL_IOSTREAM_EUSART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_EUSART_VCOM_FLOW_CONTROL_TYPE: SL_IOSTREAM_EUSART_UART_FLOW_CTRL_SOFT

  SL_IOSTREAM_EUSART_VCOM_PERIPHERAL: EUSART0
  SL_IOSTREAM_EUSART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_EUSART_VCOM_TX_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_EUSART_VCOM_TX_PIN: 8

  SL_IOSTREAM_EUSART_VCOM_RX_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_EUSART_VCOM_RX_PIN: 7

  SL_IOSTREAM_EUSART_VCOM_CTS_PORT: 0
  SL_IOSTREAM_EUSART_VCOM_CTS_PIN: 0

  SL_IOSTREAM_EUSART_VCOM_RTS_PORT: 0
  SL_IOSTREAM_EUSART_VCOM_RTS_PIN: 0

  SL_APPLICATION_PRODUCT_ID: "{0xF4, 0x5E, 0x03, 0x17, 0xD5, 0x84, 0xAD, 0xA4, 0x7D, 0xDA, 0x6C, 0x95, 0x11, 0x2F, 0x24, 0xFA}"

  SL_SIMPLE_BUTTON_BTN1_PORT: SL_GPIO_PORT_C
  SL_SIMPLE_BUTTON_BTN1_PIN: 5

  SL_CLOCK_MANAGER_HFXO_EN: 1
  SL_CLOCK_MANAGER_HFXO_CTUNE: 108
  SL_CLOCK_MANAGER_HFXO_FREQ: 39000000
  SL_CLOCK_MANAGER_HFXO_PRECISION: 10
  SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE: SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE_HFXO

  SL_RAIL_UTIL_RSSI_OFFSET: 0
